server:
  port: 8100

spring:
  application:
    name: zdz-ordersystem
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.41.157:3306/learn?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    
mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.zdzhong.zdzordersystem.model

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
